stages:
  - build
  - test

build_job:
  stage: build
  script:
    - pwd
    - cd SOSAgent
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - ./SOSAgent/target/sosagent.jar
    expire_in: 1 day

test_job:
  stage: test
  script:
  - mvn test